// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ProiectDAW;
using System;

namespace ProiectDAW.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProiectDAW.Models.User", b =>
                {
                    b.Property<string>("EmailAddress");

                    b.Property<string>("Firstname");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Role");
                  
                    b.Property<string>("ProfilePicture");

                    b.HasKey("EmailAddress");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProiectDAW.Models.GenreList", b =>
            {
                b.Property<string>("Id");

                b.Property<string>("BookGenre");

                b.Property<string>("BookId");

                b.HasKey("Id");

                b.ToTable("GenreLists");
            });

            modelBuilder.Entity("ProiectDAW.Models.Book", b =>
            {
                b.Property<string>("BookId");

                b.Property<string>("Title");

                b.Property<string>("Author");

                b.Property<string>("Year");

                b.Property<string>("Description");

                b.Property<string>("ISBN");

                b.HasKey("BookId");

                b.ToTable("Books");
            });

            modelBuilder.Entity("ProiectDAW.Models.Wishlist", b =>
            {
                b.Property<string>("WishlistId");

                b.Property<string>("UserEmail");

                b.Property<string>("BookId");

                b.HasKey("WishlistId");

                b.ToTable("Wishlists");
            });
#pragma warning restore 612, 618
        }
    }
}
